import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Login from "./Login";
import Link from 'next/link';
import Top from "@/components/Layout/Top";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet"/>
      </Head>
      <main className={`${styles.main}`}>
        <Top></Top>
        <Link href="/Login">
          Đăng nhập
        </Link>
      </main>
    </>
  );
}
